fixtures:
  repositories:
    sshkeys:
      repo: 'git://github.com/puppetlabs/puppetlabs-sshkeys_core.git'
      ref: '2.3.0'
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '8.1.0'
  symlinks:
    common: "#{source_dir}"
